# Generated by Django 4.1.4 on 2023-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="orders_history",
            field=models.JSONField(default=dict),
        ),
    ]
