# Generated by Django 4.1.4 on 2023-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_orders_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="orders_history",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
