# Generated by Django 4.1.4 on 2023-01-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="pizza",
            options={"verbose_name": "Пицца", "verbose_name_plural": "Пиццы"},
        ),
    ]
