# Generated by Django 4.1.4 on 2023-01-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pizza",
        ),
    ]
