# Generated by Django 4.1.4 on 2023-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="consist",
            field=models.ManyToManyField(to="home.consist"),
        ),
    ]
