# Generated by Django 4.1.4 on 2023-01-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_consist_product_consist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consist",
            new_name="Ingredient",
        ),
    ]
