# Generated by Django 4.1.4 on 2023-01-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_ingredient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
