# Generated by Django 4.1.4 on 2023-02-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
