# Generated by Django 4.1.4 on 2023-02-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
    ]
