# Generated by Django 4.1.4 on 2023-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="consist",
            field=models.ManyToManyField(blank=True, to="home.ingredient"),
        ),
    ]
