# Generated by Django 4.1.4 on 2023-02-20 10:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="last_name",
        ),
        migrations.AddField(
            model_name="order",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None, unique=True
            ),
        ),
    ]
