# Generated by Django 4.1.4 on 2023-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_options_remove_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
