# Generated by Django 4.1.4 on 2023-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.SmallIntegerField(
                choices=[(0, "Наличными"), (1, "Картой")], default=0
            ),
        ),
    ]
