# Generated by Django 4.1.4 on 2023-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
