# Generated by Django 4.1.4 on 2023-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
