# Generated by Django 4.1.4 on 2023-02-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="basket_history",
        ),
    ]
