# Generated by Django 4.1.4 on 2023-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_remove_order_basket_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Создан"),
                    (1, "В работе"),
                    (2, "Доставлен/Оплачен"),
                    (3, "Отменен"),
                ],
                default=0,
            ),
        ),
    ]
