# Generated by Django 4.1.4 on 2023-02-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orders_history",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
