# Generated by Django 4.1.4 on 2023-02-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_order_orders_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="orders_history",
        ),
    ]
