# Generated by Django 4.1.4 on 2023-02-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_remove_order_orders_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
